### ISSUE TITLE
Error SSL Connection

### ISSUE THREAD

**Issue by MunozVictor** [xpouyat/MK.IO#61]
Hello,

I am getting the following error occasionally on my server. I have no information about it. It has failed me for different methods, but always the same error. Is there something I should control on my server? Can you tell me more about it?

`System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Se produjo un error durante el intento de conexiÃ³n ya que la parte conectada no respondiÃ³ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiÃ³n establecida ya que el host conectado no ha podido responder..
 ---> System.Net.Sockets.SocketException (10060): Se produjo un error durante el intento de conexiÃ³n ya que la parte conectada no respondiÃ³ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiÃ³n establecida ya que el host conectado no ha podido responder.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at MK.IO.MKIOClient.ObjectContentAsync(String url, HttpMethod httpMethod)
   at MK.IO.MKIOClient.GetObjectContentAsync(String url)
   at MK.IO.Asset.AssetsOperations.GetAsync(String assetName)`

**Comment by xpouyat** [comment]
Hello, may be an issue with a firewall ? See https://github.com/xpouyat/MK.IO/issues/56

Note : please create new issues to the new repo : https://github.com/microsoft/MK.IO.

**Comment by xpouyat** [comment]
I am switching this repo to read-only. Please create a new issue on the new repo if needed.
